name: Build Node.JS Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample-packages/npm/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm ci
      - run: npm test
      - name: Commit package-lock.json changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Autobot Action
          author_email: Autobot@GitHub.com
          message: "Update package-lock.json"
          add: "package-lock.json"
